import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { theme } from "@/theme/antd";
import { hindSiliguriFonts } from "@/utils/customFonts";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Welcome to ICTSEBA",
  description: "Generated by ICTSEBA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={theme}>
      <html lang="en">
        <body
          className={`${hindSiliguriFonts.variable} font-hindSiliguri antialiased`}
        >
          <AntdRegistry>
            <Header />
            {children}
            <Footer />
          </AntdRegistry>
        </body>
      </html>
    </ConfigProvider>
  );
}
